export const TestPostDataSet = {
  content: [
    {
      post_id: 1,
      post_name: '건강 지킴이',
      price: 3000,
      email: 'teacher1@example.com',
      image_post: 'images/png/fitness_image_1.png',
      post_info:
        '운동을 사랑하는 장애인 선생님입니다. 꾸준한 운동을 통해 건강한 삶을 유지하고, 이를 다른 사람들과 나누고자 합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-01-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '철수',
      credit: null,
      user_profile: 'images/png/profile1.png',
    },
    {
      post_id: 2,
      post_name: '피트니스 전문가',
      price: 3000,
      email: 'teacher2@example.com',
      image_post: 'images/png/fitness_image_2.png',
      post_info:
        '전문적인 PT 경험이 있는 선생님입니다. 다양한 피트니스 프로그램을 통해 개인 맞춤형 지도를 제공하여 최고의 운동 효과를 보장합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-02-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '영희',
      credit: null,
      user_profile: 'images/png/profile2.png',
    },
    {
      post_id: 3,
      post_name: '운동 열정가',
      price: 3000,
      email: 'teacher3@example.com',
      image_post: 'images/png/fitness_image_3.png',
      post_info:
        '열정적인 운동 지도자입니다. 매일 새로운 도전을 통해 자신과 타인의 한계를 극복하고, 건강한 삶을 위한 지침을 제공하고자 합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-03-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '민수',
      credit: null,
      user_profile: 'images/png/profile3.png',
    },
    {
      post_id: 4,
      post_name: '친절한 코치',
      price: 3000,
      email: 'teacher4@example.com',
      image_post: 'images/png/fitness_image_4.png',
      post_info:
        '친절하고 이해심 많은 선생님입니다. 각 개인의 필요에 맞춘 세심한 지도로 건강한 운동 습관을 형성하는 데 도움을 줍니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-04-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '지우',
      credit: null,
      user_profile: 'images/png/profile4.png',
    },
    {
      post_id: 5,
      post_name: '건강 추구자',
      price: 3000,
      email: 'teacher5@example.com',
      image_post: 'images/png/fitness_image_5.png',
      post_info:
        '건강한 삶을 추구하는 PT입니다. 올바른 운동 방법과 생활 습관을 통해 건강하고 활기찬 생활을 유지할 수 있도록 도와드립니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-05-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '준호',
      credit: null,
      user_profile: 'images/png/profile5.png',
    },
    {
      post_id: 6,
      post_name: '활력 넘치는 지도자',
      price: 3000,
      email: 'teacher6@example.com',
      image_post: 'images/png/fitness_image_6.png',
      post_info:
        '활력을 불어넣는 운동 전문가입니다. 에너지 넘치는 운동 프로그램으로 몸과 마음 모두 건강해질 수 있도록 지원합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-06-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '지민',
      credit: null,
      user_profile: 'images/png/profile6.png',
    },
    {
      post_id: 7,
      post_name: '헬스 마스터',
      price: 3000,
      email: 'teacher7@example.com',
      image_post: 'images/png/fitness_image_7.png',
      post_info:
        '헬스에 대한 모든 것을 알려드립니다. 체계적이고 효과적인 헬스 트레이닝으로 최고의 성과를 낼 수 있도록 도와드립니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-07-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '민재',
      credit: null,
      user_profile: 'images/png/profile7.png',
    },
    {
      post_id: 8,
      post_name: '운동 전문가',
      price: 3000,
      email: 'teacher8@example.com',
      image_post: 'images/png/fitness_image_8.png',
      post_info:
        '운동을 통해 삶의 질을 높여드립니다. 개인별 맞춤 운동 프로그램으로 건강한 생활을 유지할 수 있도록 돕습니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-08-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '하늘',
      credit: null,
      user_profile: 'images/png/profile8.png',
    },
    {
      post_id: 9,
      post_name: 'PT 전문가',
      price: 3000,
      email: 'teacher9@example.com',
      image_post: 'images/png/fitness_image_9.png',
      post_info:
        'PT를 통해 건강을 되찾으세요. 전문적인 PT 지도로 체력과 건강을 회복할 수 있도록 지원합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-09-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '수현',
      credit: null,
      user_profile: 'images/png/profile1.png',
    },
    {
      post_id: 10,
      post_name: '생활 체육 지도자',
      price: 3000,
      email: 'teacher10@example.com',
      image_post: 'images/png/fitness_image_10.png',
      post_info:
        '생활 체육을 쉽게 배우세요. 누구나 쉽게 따라 할 수 있는 체육 프로그램을 통해 건강한 생활을 영위할 수 있습니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-10-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '나연',
      credit: null,
      user_profile: 'images/png/profile2.png',
    },
    {
      post_id: 11,
      post_name: '체력 향상 코치',
      price: 3000,
      email: 'teacher11@example.com',
      image_post: 'images/png/fitness_image_11.png',
      post_info:
        '체력 향상을 도와드립니다. 다양한 체력 강화 운동 프로그램을 통해 신체의 전반적인 체력을 높여드립니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-11-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '성훈',
      credit: null,
      user_profile: 'images/png/profile3.png',
    },
    {
      post_id: 12,
      post_name: '헬스 코치',
      price: 3000,
      email: 'teacher12@example.com',
      image_post: 'images/png/fitness_image_12.png',
      post_info:
        '헬스의 기본부터 가르쳐드립니다. 초보자부터 전문가까지 모두 만족할 수 있는 헬스 프로그램을 제공합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-12-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '민기',
      credit: null,
      user_profile: 'images/png/profile4.png',
    },
    {
      post_id: 13,
      post_name: '운동 멘토',
      price: 3000,
      email: 'teacher13@example.com',
      image_post: 'images/png/fitness_image_13.png',
      post_info:
        '운동에 대한 모든 것을 멘토링합니다. 개별 맞춤형 멘토링으로 운동 목표를 달성할 수 있도록 돕습니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-12-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '진우',
      credit: null,
      user_profile: 'images/png/profile5.png',
    },
    {
      post_id: 14,
      post_name: '재활 트레이너',
      price: 3000,
      email: 'teacher14@example.com',
      image_post: 'images/png/fitness_image_14.png',
      post_info:
        '재활 운동을 전문으로 합니다. 부상 후 회복을 돕기 위한 맞춤형 재활 프로그램을 제공합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-12-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '다현',
      credit: null,
      user_profile: 'images/png/profile6.png',
    },
    {
      post_id: 15,
      post_name: '심신 강화 지도자',
      price: 3000,
      email: 'teacher15@example.com',
      image_post: 'images/png/fitness_image_15.png',
      post_info:
        '심신을 강화하는 운동을 지도합니다. 신체와 마음을 모두 건강하게 만드는 전인적 운동 프로그램을 제공합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-12-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '재윤',
      credit: null,
      user_profile: 'images/png/profile7.png',
    },
    {
      post_id: 16,
      post_name: '건강 회복 트레이너',
      price: 3000,
      email: 'teacher16@example.com',
      image_post: 'images/png/fitness_image_16.png',
      post_info:
        '건강 회복을 돕는 트레이너입니다. 개인별 맞춤형 회복 프로그램으로 빠르고 효과적인 건강 회복을 지원합니다.',
      total_number: 5,
      f: 0.2,
      state: 1,
      category_id: 3001,
      start_at: '2024-12-01',
      end_at: '2024-12-31',
      like: false,
      nick_name: '예빈',
      credit: null,
      user_profile: 'images/png/profile8.png',
    },
  ],
  pageable: {
    pageNumber: 0,
    pageSize: 16,
    sort: [
      {
        direction: 'ASC',
        property: 'postId',
        ignoreCase: false,
        nullHandling: 'NATIVE',
        descending: false,
        ascending: true,
      },
    ],
    offset: 0,
    paged: true,
    unpaged: false,
  },
  last: true,
  totalElements: 16,
  totalPages: 1,
  size: 16,
  number: 0,
  sort: [
    {
      direction: 'ASC',
      property: 'postId',
      ignoreCase: false,
      nullHandling: 'NATIVE',
      descending: false,
      ascending: true,
    },
  ],
  first: true,
  numberOfElements: 16,
  empty: false,
};
